name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4

      - name: Show files (debug)
        run: |
          pwd
          ls -la
